services:
  # Laravel Backend API (Docker)
  - type: web
    name: multilingual-resume-backend
    runtime: docker
    repo: https://github.com/saud06/multilingual-resume-generator.git
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    # Environment variables set manually in Render dashboard

  # Next.js Frontend
  - type: web
    name: multilingual-resume-frontend
    runtime: node
    repo: https://github.com/saud06/multilingual-resume-generator.git
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    # Environment variables set manually in Render dashboard
